import type { Metadata } from "next";
import {openSans} from '@/app/ui/fonts'
import "./globals.css";


export const metadata: Metadata = {
  title: "Teachable Machine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} antialiased bg-white`}>{children}</body>
    </html>
  );
}
